defaultContentLanguage = 'pt-br'
[languages]
  [languages.pt]
    languageCode = 'pt-br'
    languageName = 'Portuguese'
    title = 'Documentação do Projeto'
    weight = 1
    [languages.pt.params]
      subtitle = 'Referência, Tutoriais and Explicações'