defaultContentLanguage = 'pt'
defaultContentLanguageInSubdir = false
[languages]
  [languages.pt]
    languageCode = 'pt'
    languageDirection = 'ltr'
    languageName = 'Portuguese'
    title = 'Documentação do Projeto'
    weight = 1
    [languages.pt.params]
      subtitle = 'Referência, Tutoriais and Explicações'